databases:
  - name: pmclub
    databaseName: pmclub
    user: pmclub

services:
  - type: web
    name: pmclub
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn pmclub.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pmclub
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
